# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  database: chat_room_development
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: chat_room_development
  host: localhost
  pool: 5
  timeout: 5000
  username: ubuntu

test:
  adapter: postgresql
  encoding: utf8
  database: chat_room_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: chat_room_production
  pool: 5
  timeout: 5000